name: Wooldridge Custom Woodturning
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8286788
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#3A2514'
    - '#D0944B'
    - '#896330'
    - '#A0918C'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
